#!/bin/sh

CURRENT_DIR=$( echo $PWD )

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

PROJECT_DIR=$( cd $SCRIPTS_DIR && cd .. && pwd )
APP_DIR=$PROJECT_DIR/app
CONTENT_DIR=$PROJECT_DIR/app/templates/project

VERSION=1 # Default to 1

gcloud -h >/dev/null 2>&1 || { echo >&2 "\nIt looks like the Google App Engine SDK isn't installed. You're going to need it: https://developers.google.com/appengine/downloads\n"; exit 1; }

if [ ! $# -gt 0 ]; then
    echo 'You did not provide a command; see `drawbridge help`'; exit 1;
else
    COMMAND=$1
fi

case "$COMMAND" in
    'update')
        echo 'Attempting to update Drawbridge...'
        cd "$PROJECT_DIR" && git checkout master && git pull
    ;;
    'local')
        echo 'Running local server...'
        echo ''
        echo "Clearing old project files"
        echo ''

        for item in "$CONTENT_DIR"/*
        do
            if [ -f "$item" ]; then
                rm "$item"
            else
                rm -R "$item"
            fi
        done

        echo ''
        echo "Copying files from $CURRENT_DIR to $CONTENT_DIR"
        echo ''

        for item in "$CURRENT_DIR"/*
        do
            if [ -f "$item" ]; then
                cp "$item" $CONTENT_DIR
            else
                cp -R "$item" $CONTENT_DIR
            fi
        done

        echo ''
        echo "Building app.yaml for local app"
        echo ''

        cat "$PROJECT_DIR"/app.yaml.template | sed 's/__APP_NAME__/local-app/' | sed 's/__VERSION__/'"$VERSION_NAME"'/' > "$PROJECT_DIR"/app.yaml

        dev_appserver.py "$PROJECT_DIR"
    ;;
    'help')
        echo ""
        echo "------------------------------ -=T\__/T=- ------------------------------"
        echo ""
        echo ""
        echo ""
        echo "Welcome errant Knight!"
        echo ""
        echo "To update Drawbridge, enter: 'drawbridge update'"
        echo ""
        echo "To deploy, simply go to the folder of files you wish to deploy and execute: "
        echo ""
        echo "'drawbridge deploy app-id-here project-name-here'"
        echo ""
        echo "Need more help? Visit https://github.com/leftfieldlabs/drawbridge"
        echo ""
        echo ""
        echo "------------------------------ -=T\__/T=- ------------------------------"
        echo ""
    ;;
    'deploy')

        if [ ! $# -ge 3 ]; then
            echo 'You did not provide all necessary arguments; see `drawbridge help`'; exit 1;
        fi

        APP_NAME=$2 # Base space for projects
        VERSION_NAME=$3 # Up to 10 versions per App ID
        BYPASS_WARNING=$4

        if [ "$BYPASS_WARNING" != '--bypass' ]; then
            echo "Are you positive you want to deploy $CURRENT_DIR? [Y/n]"
            read answer

            if [ $answer == "n" ] || [ $answer == "N" ]; then
                exit 1;
            fi
        fi

        echo ''
        echo "Targeting $CURRENT_DIR"
        echo ''

        echo ''
        echo "Checking for git hash"
        echo ''

        cd "$CURRENT_DIR" && git rev-parse --short HEAD >/dev/null 2>&1 || {
            echo >&2 "\nLooks like git is not enabled in this directory. We're gonna default to version '1', just so you know.\n"
            VERSION=0
        }

        if [ $VERSION -eq 0 ]; then
            VERSION=1
        else
            VERSION=$(cd "$CURRENT_DIR" && git rev-parse --short HEAD)
        fi


        echo ''
        echo "Clearing old project files"
        echo ''

        for item in "$CONTENT_DIR"/*
        do
            if [ -f "$item" ]; then
                rm "$item"
            else
                rm -R "$item"
            fi
        done

        echo ''
        echo "Copying files from $CURRENT_DIR to $CONTENT_DIR"
        echo ''

        for item in "$CURRENT_DIR"/*
        do
            if [ -f "$item" ]; then
                cp "$item" $CONTENT_DIR
            else
                cp -R "$item" $CONTENT_DIR
            fi
        done

        echo ''
        echo "Building app.yaml for $VERSION_NAME"
        echo ''

        cat "$PROJECT_DIR"/app.yaml.template > "$PROJECT_DIR"/app.yaml

        echo ''
        echo "Deploying $VERSION_NAME"
        echo ''

        gcloud config set project "$APP_NAME"
        gcloud app deploy "$PROJECT_DIR"/app.yaml --version="$VERSION_NAME"

        echo ''
        echo "Cleaning up"
        echo ''

        echo ''
        echo "Deleting previous app.yaml"
        echo ''

        rm -f "$PROJECT_DIR"/app.yaml

        echo ''
        echo "Visit your site at https://$VERSION_NAME-dot-$APP_NAME.appspot.com"
        echo ''
    ;;
    *)
        echo "Sorry, this command was not recognized. Type 'drawbridge help'."
    ;;
esac
