#!/bin/sh

CURRENT_DIR=$( echo $PWD )
SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_DIR=$( cd $SCRIPTS_DIR && cd .. && pwd )
APP_DIR=$PROJECT_DIR/app

echo ''
echo "Installing to /usr/local/bin"
echo ''

ln -s "$SCRIPTS_DIR"/drawbridge /usr/local/bin/drawbridge
