#!/bin/sh

CURRENT_DIR=$( echo $PWD )
PROJECT_DIR=~/.drawbridge
SCRIPTS_DIR=$PROJECT_DIR/scripts
APP_DIR=$PROJECT_DIR/app
COMMAND=/usr/local/bin/drawbridge

echo ''
echo 'Checking for existing install...'
echo ''

if [ -f "$COMMAND" ]; then
    echo 'Drawbridge already installed; run `drawbridge update`'
    exit 1;
fi

echo ''
echo "Cloning repo..."
echo ''

if [ ! -d "$PROJECT_DIR" ]; then
    mkdir "$PROJECT_DIR"
    git clone git@github.com:leftfieldlabs/drawbridge.git "$PROJECT_DIR"
fi

echo ''
echo "Installing to /usr/local/bin"
echo ''

ln -s "$SCRIPTS_DIR"/drawbridge "$COMMAND"
