#!/bin/sh

dev_appserver.py -h >/dev/null 2>&1 || { echo >&2 "\nIt looks like the Google App Engine SDK isn't installed. You're going to need it: https://developers.google.com/appengine/downloads\n"; exit 1; }

CURRENT_DIR=$( echo $PWD )
SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_DIR=$( cd $SCRIPTS_DIR && cd .. && pwd )
APP_DIR=$( cd $PROJECT_DIR/app && pwd )

if [ -f "$PROJECT_DIR/app.yaml" ]; then
    echo ''
    echo 'Found app.yaml, starting server...'
    echo ''
    dev_appserver.py $PROJECT_DIR
else
    echo ''
    echo 'app.yaml does not exist; try running ./scripts/install\n'; exit 1;
fi
