#!/bin/sh

CURRENT_DIR=$( echo $PWD )

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
#SCRIPTS_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
PROJECT_DIR=$( cd $SCRIPTS_DIR && cd .. && pwd )
APP_DIR=$PROJECT_DIR/app
CONTENT_DIR=$PROJECT_DIR/app/templates/project

VERSION=1 # Default to 1

# TODO: Find this
#appcfg.py >/dev/null 2>&1 || { echo >&2 "\nHmm... doesn't look like you have Google App Engine installed\n"; exit 1;}

if [ ! $# -eq 2 ]; then
    echo 'You did not provide a command and an app name'; exit 1;
else
    COMMAND=$1
    APP_NAME=$2
fi

if [ ! "$COMMAND" == 'deploy' ]; then
    echo "Command '$COMMAND' not recognized"; exit 1;
else
    echo ''
    echo "Targeting $CURRENT_DIR"
    echo ''

    echo ''
    echo "Checking for git hash"
    echo ''

    cd "$CURRENT_DIR" && git rev-parse --short HEAD >/dev/null 2>&1 || { echo >&2 "\nLooks like git is not enabled in this directory. Make sure you have git and at least one commit\n"; exit 1; }

    VERSION=$(cd "$CURRENT_DIR" && git rev-parse --short HEAD)

    echo ''
    echo "Clearing old project files"
    echo ''

    for item in "$CONTENT_DIR"/*
    do
        if [ -f "$item" ]; then
            rm "$item"
        else
            rm -R "$item"
        fi
    done

    echo ''
    echo "Copying files from $CURRENT_DIR to $CONTENT_DIR"
    echo ''

    for item in "$CURRENT_DIR"/*
    do
        if [ -f "$item" ]; then
            cp "$item" $CONTENT_DIR
        else
            cp -R "$item" $CONTENT_DIR
        fi
    done

    echo ''
    echo "Building app.yaml for $APP_NAME"
    echo ''

    cat "$PROJECT_DIR"/app.yaml.template | sed 's/__APP_NAME__/'"$APP_NAME"'/' | sed 's/__VERSION__/'"$VERSION"'/' > "$PROJECT_DIR"/app.yaml

    echo ''
    echo "Deploying $APP_NAME"
    echo ''

    appcfg.py update $PROJECT_DIR

    echo ''
    echo "Cleaning up"
    echo ''

    echo ''
    echo "Deleting previous app.yaml"
    echo ''

    rm -f "$PROJECT_DIR"/app.yaml
fi
