#!/bin/sh

CURRENT_DIR=$( echo $PWD )

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPTS_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"

PROJECT_DIR=$( cd $SCRIPTS_DIR && cd .. && pwd )
APP_DIR=$PROJECT_DIR/app
CONTENT_DIR=$PROJECT_DIR/app/templates/project

VERSION=1 # Default to 1

APPCFG_PATH="$(which appcfg.py)"

if [ ! ${#APPCFG_PATH} -gt 0 ]; then
    echo "Doesn't look like you have Google App Engine SDK installed. Go to https://cloud.google.com/appengine/downloads?hl=en"; exit 1;
fi

if [ ! $# -gt 0 ]; then
    echo 'You did not provide a command'; exit 1;
else
    COMMAND=$1
fi

case "$COMMAND" in
    'update')
        echo 'Attempting to update Vault...'
        cd "$PROJECT_DIR" && git pull
    ;;
    'local')
        echo 'Running local server...'
        echo ''
        echo "Clearing old project files"
        echo ''

        for item in "$CONTENT_DIR"/*
        do
            if [ -f "$item" ]; then
                rm "$item"
            else
                rm -R "$item"
            fi
        done

        echo ''
        echo "Copying files from $CURRENT_DIR to $CONTENT_DIR"
        echo ''

        for item in "$CURRENT_DIR"/*
        do
            if [ -f "$item" ]; then
                cp "$item" $CONTENT_DIR
            else
                cp -R "$item" $CONTENT_DIR
            fi
        done

        echo ''
        echo "Building app.yaml for local app"
        echo ''

        cat "$PROJECT_DIR"/app.yaml.template | sed 's/__APP_NAME__/local-app/' | sed 's/__VERSION__/'"$VERSION_NAME"'/' > "$PROJECT_DIR"/app.yaml

        dev_appserver.py "$PROJECT_DIR"
    ;;
    'help')
        echo ""
        echo "------------------------------ -=()=- ------------------------------"
        echo ""
        echo ""
        echo ""
        echo "Welcome Vault Dweller!"
        echo ""
        echo "To update Vault, enter: 'vault update'"
        echo ""
        echo "To deploy, simply go to the folder of files you wish to deploy and enter: "
        echo ""
        echo "'vault deploy app-id-here'"
        echo ""
        echo "where 'app-id-here' is your own app id"
        echo ""
        echo "Need more help? Email sebastian@leftfieldlabs.com"
        echo ""
        echo ""
        echo "------------------------------ -=()=- ------------------------------"
        echo ""
    ;;
    'deploy')

        echo "Are you positive you want to deploy $CURRENT_DIR? [Y/n]"
        read answer

        if [ ! $# -eq 2 ]; then
            echo 'You did not provide an app id'; exit 1;
        fi

        VERSION_NAME=$2
        APP_NAME="lflwebreview"

        echo ''
        echo "Targeting $CURRENT_DIR"
        echo ''

        echo ''
        echo "Checking for git hash"
        echo ''

        cd "$CURRENT_DIR" && git rev-parse --short HEAD >/dev/null 2>&1 || {
            echo >&2 "\nLooks like git is not enabled in this directory. We're gonna default to version '1', just so you know.\n"
            VERSION=0
        }

        if [ $VERSION -eq 0 ]; then
            VERSION=1
        else
            VERSION=$(cd "$CURRENT_DIR" && git rev-parse --short HEAD)
        fi


        echo ''
        echo "Clearing old project files"
        echo ''

        for item in "$CONTENT_DIR"/*
        do
            if [ -f "$item" ]; then
                rm "$item"
            else
                rm -R "$item"
            fi
        done

        echo ''
        echo "Copying files from $CURRENT_DIR to $CONTENT_DIR"
        echo ''

        for item in "$CURRENT_DIR"/*
        do
            if [ -f "$item" ]; then
                cp "$item" $CONTENT_DIR
            else
                cp -R "$item" $CONTENT_DIR
            fi
        done

        echo ''
        echo "Building app.yaml for $VERSION_NAME"
        echo ''

        cat "$PROJECT_DIR"/app.yaml.template | sed 's/__APP_NAME__/'"$APP_NAME"'/' | sed 's/__VERSION__/'"$VERSION_NAME"'/' > "$PROJECT_DIR"/app.yaml

        echo ''
        echo "Deploying $VERSION_NAME"
        echo ''

        appcfg.py update $PROJECT_DIR

        echo ''
        echo "Cleaning up"
        echo ''

        echo ''
        echo "Deleting previous app.yaml"
        echo ''

        rm -f "$PROJECT_DIR"/app.yaml
    ;;
    *)
        echo "Sorry, this command was not recognized. Type 'vault help'."
    ;;
esac
